Update build-android-gsi.yml

diff --git a/.github/workflows/build-android-gsi.yml b/.github/workflows/build-android-gsi.yml
--- a/.github/workflows/build-android-gsi.yml
+++ b/.github/workflows/build-android-gsi.yml
@@ -65,7 +65,7 @@ jobs:
       run: |
         source $GITHUB_ENV
         echo "Build Directory:"
-        ls -l build
+        ls -l build || echo "Build directory not found"
 
     - name: Verify Build Directory
       run: |
